name: Secret Demo Wrokflow
on: 
  workflow_dispatch:
env:
    DAY_OF_WEEK: Monday   
jobs:
  example-jobs:
    name: Variables & Secrets Demo  Job
    runs-on: ubuntu-latest
    env:
     Greeting: Hello2        
    steps:
      - name: Print value of Secrets 
        run: |
         echo "Value of Greetings is :${{ env.Greeting }}"
         echo "Value of Greetings is :$Greeting"
         echo "Value of Day of Week  is :${{ env.DAY_OF_WEEK }}"   
         echo "Repo Secret is :${{ secrets.SECRET1 }}"            
